### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Cypher1** [unsw-cse-soc/Data-curation-API#1]
Hi, I was just wondering if there was documentation for this API anywhere? There doesn't seem to be a wiki attached to this repo or any links or explanation in the README.

Could these be added?

Thanks

**Comment by aminbeheshti** [comment]
Hi Joshua,

The link for the paper (HERE
<http://papers.www2017.com.au.s3-website-ap-southeast-2.amazonaws.com/companion/p165.pdf>)
and technical report (HERE <https://arxiv.org/pdf/1612.03277.pdf>) can be
found on the main page.
Please let me know if you need further assistance..

Cheers,
Amin <http://www.cse.unsw.edu.au/~sbeheshti/>

**Comment by Cypher1** [comment]
Thanks @aminbeheshti. I was under the impression that the API was a web API (as it is being used in the Web apps course) and therefore needed a rather different form of documentation.

Is there a plan to make the documentation more accessible? It is currently an almost 50 page appendix to the linked paper. A website would be appreciated.

Thanks

**Comment by aminbeheshti** [comment]
You should find it in the appendix of the technical report. Cheers
